// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: addressbook.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.tutorial.protos;

@kotlin.jvm.JvmName("-initializeperson")
public inline fun person(block: com.example.tutorial.protos.PersonKt.Dsl.() -> kotlin.Unit): com.example.tutorial.protos.Person =
  com.example.tutorial.protos.PersonKt.Dsl._create(com.example.tutorial.protos.Person.newBuilder()).apply { block() }._build()
/**
 * ```
 * [START messages]
 * ```
 *
 * Protobuf type `tutorial.Person`
 */
public object PersonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.tutorial.protos.Person.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.tutorial.protos.Person.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.tutorial.protos.Person = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * ```
     * Unique ID number for this person.
     * ```
     *
     * `int32 id = 2;`
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * ```
     * Unique ID number for this person.
     * ```
     *
     * `int32 id = 2;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string email = 3;`
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * `string email = 3;`
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PhonesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .tutorial.Person.PhoneNumber phones = 4;`
     */
     public val phones: com.google.protobuf.kotlin.DslList<com.example.tutorial.protos.Person.PhoneNumber, PhonesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPhonesList()
      )
    /**
     * `repeated .tutorial.Person.PhoneNumber phones = 4;`
     * @param value The phones to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPhones")
    public fun com.google.protobuf.kotlin.DslList<com.example.tutorial.protos.Person.PhoneNumber, PhonesProxy>.add(value: com.example.tutorial.protos.Person.PhoneNumber) {
      _builder.addPhones(value)
    }
    /**
     * `repeated .tutorial.Person.PhoneNumber phones = 4;`
     * @param value The phones to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPhones")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.tutorial.protos.Person.PhoneNumber, PhonesProxy>.plusAssign(value: com.example.tutorial.protos.Person.PhoneNumber) {
      add(value)
    }
    /**
     * `repeated .tutorial.Person.PhoneNumber phones = 4;`
     * @param values The phones to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPhones")
    public fun com.google.protobuf.kotlin.DslList<com.example.tutorial.protos.Person.PhoneNumber, PhonesProxy>.addAll(values: kotlin.collections.Iterable<com.example.tutorial.protos.Person.PhoneNumber>) {
      _builder.addAllPhones(values)
    }
    /**
     * `repeated .tutorial.Person.PhoneNumber phones = 4;`
     * @param values The phones to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPhones")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.tutorial.protos.Person.PhoneNumber, PhonesProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.tutorial.protos.Person.PhoneNumber>) {
      addAll(values)
    }
    /**
     * `repeated .tutorial.Person.PhoneNumber phones = 4;`
     * @param index The index to set the value at.
     * @param value The phones to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPhones")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.tutorial.protos.Person.PhoneNumber, PhonesProxy>.set(index: kotlin.Int, value: com.example.tutorial.protos.Person.PhoneNumber) {
      _builder.setPhones(index, value)
    }
    /**
     * `repeated .tutorial.Person.PhoneNumber phones = 4;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPhones")
    public fun com.google.protobuf.kotlin.DslList<com.example.tutorial.protos.Person.PhoneNumber, PhonesProxy>.clear() {
      _builder.clearPhones()
    }


    /**
     * `.google.protobuf.Timestamp last_updated = 5;`
     */
    public var lastUpdated: com.google.protobuf.Timestamp
      @JvmName("getLastUpdated")
      get() = _builder.getLastUpdated()
      @JvmName("setLastUpdated")
      set(value) {
        _builder.setLastUpdated(value)
      }
    /**
     * `.google.protobuf.Timestamp last_updated = 5;`
     */
    public fun clearLastUpdated() {
      _builder.clearLastUpdated()
    }
    /**
     * `.google.protobuf.Timestamp last_updated = 5;`
     * @return Whether the lastUpdated field is set.
     */
    public fun hasLastUpdated(): kotlin.Boolean {
      return _builder.hasLastUpdated()
    }
  }
  @kotlin.jvm.JvmName("-initializephoneNumber")
  public inline fun phoneNumber(block: com.example.tutorial.protos.PersonKt.PhoneNumberKt.Dsl.() -> kotlin.Unit): com.example.tutorial.protos.Person.PhoneNumber =
    com.example.tutorial.protos.PersonKt.PhoneNumberKt.Dsl._create(com.example.tutorial.protos.Person.PhoneNumber.newBuilder()).apply { block() }._build()
  /**
   * Protobuf type `tutorial.Person.PhoneNumber`
   */
  public object PhoneNumberKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.example.tutorial.protos.Person.PhoneNumber.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.example.tutorial.protos.Person.PhoneNumber.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.example.tutorial.protos.Person.PhoneNumber = _builder.build()

      /**
       * `string number = 1;`
       */
      public var number: kotlin.String
        @JvmName("getNumber")
        get() = _builder.getNumber()
        @JvmName("setNumber")
        set(value) {
          _builder.setNumber(value)
        }
      /**
       * `string number = 1;`
       */
      public fun clearNumber() {
        _builder.clearNumber()
      }

      /**
       * `.tutorial.Person.PhoneType type = 2;`
       */
      public var type: com.example.tutorial.protos.Person.PhoneType
        @JvmName("getType")
        get() = _builder.getType()
        @JvmName("setType")
        set(value) {
          _builder.setType(value)
        }
      public var typeValue: kotlin.Int
        @JvmName("getTypeValue")
        get() = _builder.getTypeValue()
        @JvmName("setTypeValue")
        set(value) {
          _builder.setTypeValue(value)
        }
      /**
       * `.tutorial.Person.PhoneType type = 2;`
       */
      public fun clearType() {
        _builder.clearType()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.tutorial.protos.Person.copy(block: com.example.tutorial.protos.PersonKt.Dsl.() -> kotlin.Unit): com.example.tutorial.protos.Person =
  com.example.tutorial.protos.PersonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun com.example.tutorial.protos.Person.PhoneNumber.copy(block: com.example.tutorial.protos.PersonKt.PhoneNumberKt.Dsl.() -> kotlin.Unit): com.example.tutorial.protos.Person.PhoneNumber =
  com.example.tutorial.protos.PersonKt.PhoneNumberKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.tutorial.protos.PersonOrBuilder.lastUpdatedOrNull: com.google.protobuf.Timestamp?
  get() = if (hasLastUpdated()) getLastUpdated() else null

